######################################################################
# Automatically generated by qmake (2.01a) Mon Aug 27 11:20:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src tests
INCLUDEPATH += . src tests
QT += testlib

# Input
HEADERS += src/mustache.h tests/test_mustache.h
SOURCES += src/mustache.cpp tests/test_mustache.cpp
